### ISSUE TITLE
Getting error: `ModuleNotFoundError: No module named 'qtpy'`

### ISSUE THREAD

**Issue by roaldarbol** [conda-forge/deeplabcut-feedstock#35]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Hi @hmaarrfk!
Thanks for maintaining this recipe!
I just attempted to install DLC with pixi - it installed well, but on running it I get `qtpy` as a missing dependency.

````sh
❯ pixi global install deeplabcut
Global environments as specified in '/Users/roaldarbol/.pixi/manifests/pixi-global.toml'
└── deeplabcut: 2.3.10 (installed)
    └─ exposes: dlc, deeplabcut

~ took 58s
❯ deeplabcut
2024-11-26 11:46:01.066713: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "/Users/roaldarbol/.pixi/envs/deeplabcut/bin/deeplabcut", line 10, in <module>
    sys.exit(launch_dlc())
             ^^^^^^^^^^^^
  File "/Users/roaldarbol/.pixi/envs/deeplabcut/lib/python3.11/site-packages/deeplabcut/gui/launch_script.py", line 29, in launch_dlc
    import qtpy.QtWidgets as QtWidgets
ModuleNotFoundError: No module named 'qtpy'
````

By the way, I'd be happy to help maintaining the recipe if it helps - I'm still learning, and I don't have much experience with patches, but would be happy to learn (in the coming year). :-)

### Installed packages

```shell
❯ mamba list -p ~/.pixi/envs/deeplabcut
List of packages in environment: "/Users/roaldarbol/.pixi/envs/deeplabcut"

  Name                                  Version             Build                    Channel
──────────────────────────────────────────────────────────────────────────────────────────────────
  absl-py                               2.1.0               pyhd8ed1ab_0             conda-forge
  aiohappyeyeballs                      2.4.3               pyhd8ed1ab_0             conda-forge
  aiohttp                               3.11.7              py311ha3cf9ac_0          conda-forge
  aiosignal                             1.3.1               pyhd8ed1ab_0             conda-forge
  aom                                   3.7.1               h93d8f39_0               conda-forge
  astunparse                            1.6.3               pyhd8ed1ab_2             conda-forge
  attrs                                 24.2.0              pyh71513ae_0             conda-forge
  blinker                               1.9.0               pyhff2d567_0             conda-forge
  blosc                                 1.21.5              heccf04b_0               conda-forge
  brotli                                1.1.0               h00291cd_2               conda-forge
  brotli-bin                            1.1.0               h00291cd_2               conda-forge
  brotli-python                         1.1.0               py311hd89902b_2          conda-forge
  brunsli                               0.1                 h046ec9c_0               conda-forge
  bzip2                                 1.0.8               hfdf4475_7               conda-forge
  c-ares                                1.34.3              hf13058a_1               conda-forge
  c-blosc2                              2.12.0              h0ae8482_0               conda-forge
  ca-certificates                       2024.8.30           h8857fd0_0               conda-forge
  cached-property                       1.5.2               hd8ed1ab_1               conda-forge
  cached_property                       1.5.2               pyha770c72_1             conda-forge
  cachetools                            5.5.0               pyhd8ed1ab_0             conda-forge
  cairo                                 1.18.0              h9f650ed_2               conda-forge
  certifi                               2024.8.30           pyhd8ed1ab_0             conda-forge
  cffi                                  1.17.1              py311h137bacd_0          conda-forge
  charls                                2.4.2               he965462_0               conda-forge
  charset-normalizer                    3.4.0               pyhd8ed1ab_0             conda-forge
  click                                 8.1.7               unix_pyh707e725_0        conda-forge
  colorama                              0.4.6               pyhd8ed1ab_0             conda-forge
  contourpy                             1.3.1               py311h4e34fa0_0          conda-forge
  cryptography                          43.0.3              py311h968b48f_0          conda-forge
  cycler                                0.12.1              pyhd8ed1ab_0             conda-forge
  dav1d                                 1.2.1               h0dc2134_0               conda-forge
  deeplabcut                            2.3.10              pyhd8ed1ab_0             conda-forge
  dlclibrary                            0.0.7               pyhd8ed1ab_0             conda-forge
  ffmpeg                                6.1.1               gpl_haae13e6_101         conda-forge
  filelock                              3.16.1              pyhd8ed1ab_0             conda-forge
  filterpy                              1.4.5               py_1                     conda-forge
  flatbuffers                           23.5.26             he965462_1               conda-forge
  font-ttf-dejavu-sans-mono             2.37                hab24e00_0               conda-forge
  font-ttf-inconsolata                  3.000               h77eed37_0               conda-forge
  font-ttf-source-code-pro              2.038               h77eed37_0               conda-forge
  font-ttf-ubuntu                       0.83                h77eed37_3               conda-forge
  fontconfig                            2.15.0              h37eeddb_1               conda-forge
  fonts-conda-ecosystem                 1                   0                        conda-forge
  fonts-conda-forge                     1                   0                        conda-forge
  fonttools                             4.55.0              py311ha3cf9ac_0          conda-forge
  freetype                              2.12.1              h60636b9_2               conda-forge
  fribidi                               1.0.10              hbcb3906_0               conda-forge
  frozenlist                            1.5.0               py311h1314207_0          conda-forge
  fsspec                                2024.10.0           pyhff2d567_0             conda-forge
  gast                                  0.5.5               pyhd8ed1ab_0             conda-forge
  geos                                  3.13.0              hac325c4_0               conda-forge
  gettext                               0.22.5              hdfe23c8_3               conda-forge
  gettext-tools                         0.22.5              hdfe23c8_3               conda-forge
  giflib                                5.2.2               h10d778d_0               conda-forge
  gmp                                   6.3.0               hf036a51_2               conda-forge
  gnutls                                3.7.9               h1951705_0               conda-forge
  google-auth                           2.36.0              pyhff2d567_0             conda-forge
  google-auth-oauthlib                  1.2.1               pyhd8ed1ab_0             conda-forge
  google-pasta                          0.2.0               pyhd8ed1ab_1             conda-forge
  graphite2                             1.3.13              h73e2aa4_1003            conda-forge
  grpcio                                1.59.3              py311h78ff076_0          conda-forge
  h2                                    4.1.0               pyhd8ed1ab_0             conda-forge
  h5py                                  3.12.1              nompi_py311h82f1de1_102  conda-forge
  harfbuzz                              8.5.0               h053f038_0               conda-forge
  hdf5                                  1.14.3              nompi_h687a608_105       conda-forge
  hpack                                 4.0.0               pyh9f0ad1d_0             conda-forge
  huggingface_hub                       0.26.2              pyh0610db2_0             conda-forge
  hyperframe                            6.0.1               pyhd8ed1ab_0             conda-forge
  icu                                   73.2                hf5e326d_0               conda-forge
  idna                                  3.10                pyhd8ed1ab_0             conda-forge
  imagecodecs                           2024.1.1            py311h5e2a27e_0          conda-forge
  imageio                               2.36.0              pyh12aca89_1             conda-forge
  imageio-ffmpeg                        0.5.1               pyhd8ed1ab_0             conda-forge
  imgaug                                0.4.0               pyhd8ed1ab_1             conda-forge
  importlib-metadata                    8.5.0               pyha770c72_0             conda-forge
  jasper                                4.2.4               hb10263b_0               conda-forge
  joblib                                1.4.2               pyhd8ed1ab_0             conda-forge
  jxrlib                                1.1                 h10d778d_3               conda-forge
  keras                                 2.15.0              pyhd8ed1ab_0             conda-forge
  kiwisolver                            1.4.7               py311hf2f7c97_0          conda-forge
  krb5                                  1.21.3              h37d8d59_0               conda-forge
  lame                                  3.100               hb7f2c08_1003            conda-forge
  lazy-loader                           0.4                 pyhd8ed1ab_1             conda-forge
  lazy_loader                           0.4                 pyhd8ed1ab_1             conda-forge
  lcms2                                 2.16                ha2f27b4_0               conda-forge
  lerc                                  4.0.0               hb486fe8_0               conda-forge
  libabseil                             20230802.1          cxx17_h048a20a_0         conda-forge
  libaec                                1.1.3               h73e2aa4_0               conda-forge
  libasprintf                           0.22.5              hdfe23c8_3               conda-forge
  libasprintf-devel                     0.22.5              hdfe23c8_3               conda-forge
  libass                                0.17.1              h80904bb_1               conda-forge
  libavif16                             1.0.3               h257e3bc_1               conda-forge
  libblas                               3.9.0               25_osx64_openblas        conda-forge
  libbrotlicommon                       1.1.0               h00291cd_2               conda-forge
  libbrotlidec                          1.1.0               h00291cd_2               conda-forge
  libbrotlienc                          1.1.0               h00291cd_2               conda-forge
  libcblas                              3.9.0               25_osx64_openblas        conda-forge
  libcurl                               8.10.1              h58e7537_0               conda-forge
  libcxx                                19.1.4              hf95d169_0               conda-forge
  libdeflate                            1.19                ha4e1b8e_0               conda-forge
  libedit                               3.1.20191231        h0678c8f_2               conda-forge
  libev                                 4.33                h10d778d_2               conda-forge
  libexpat                              2.6.4               h240833e_0               conda-forge
  libffi                                3.4.2               h0d85af4_5               conda-forge
  libgettextpo                          0.22.5              hdfe23c8_3               conda-forge
  libgettextpo-devel                    0.22.5              hdfe23c8_3               conda-forge
  libgfortran                           5.0.0               13_2_0_h97931a8_3        conda-forge
  libgfortran5                          13.2.0              h2873a65_3               conda-forge
  libglib                               2.82.2              hb6ef654_0               conda-forge
  libgrpc                               1.59.3              ha7f534c_0               conda-forge
  libhwloc                              2.11.2              default_hb6fbd3b_1000    conda-forge
  libiconv                              1.17                hd75f5a5_2               conda-forge
  libidn2                               2.3.7               h10d778d_0               conda-forge
  libintl                               0.22.5              hdfe23c8_3               conda-forge
  libintl-devel                         0.22.5              hdfe23c8_3               conda-forge
  libjpeg-turbo                         3.0.0               h0dc2134_1               conda-forge
  liblapack                             3.9.0               25_osx64_openblas        conda-forge
  liblapacke                            3.9.0               25_osx64_openblas        conda-forge
  libllvm14                             14.0.6              hc8e404f_4               conda-forge
  libnghttp2                            1.64.0              hc7306c3_0               conda-forge
  libopenblas                           0.3.28              openmp_hbf64a52_1        conda-forge
  libopencv                             4.9.0               py311h2c8e0bd_5          conda-forge
  libopenvino                           2023.2.0            h113ac47_4               conda-forge
  libopenvino-auto-batch-plugin         2023.2.0            h9adb129_4               conda-forge
  libopenvino-auto-plugin               2023.2.0            h9adb129_4               conda-forge
  libopenvino-hetero-plugin             2023.2.0            hfe2fe54_4               conda-forge
  libopenvino-intel-cpu-plugin          2023.2.0            h113ac47_4               conda-forge
  libopenvino-ir-frontend               2023.2.0            hfe2fe54_4               conda-forge
  libopenvino-onnx-frontend             2023.2.0            h3f04633_4               conda-forge
  libopenvino-paddle-frontend           2023.2.0            h3f04633_4               conda-forge
  libopenvino-pytorch-frontend          2023.2.0            hd427752_4               conda-forge
  libopenvino-tensorflow-frontend       2023.2.0            he7d75b5_4               conda-forge
  libopenvino-tensorflow-lite-frontend  2023.2.0            hd427752_4               conda-forge
  libopus                               1.3.1               hc929b4f_1               conda-forge
  libpng                                1.6.44              h4b8f8c9_0               conda-forge
  libprotobuf                           4.24.4              hc4f2305_0               conda-forge
  libre2-11                             2023.09.01          h4694dbf_1               conda-forge
  libsodium                             1.0.20              hfdf4475_0               conda-forge
  libsqlite                             3.47.0              h2f8c449_1               conda-forge
  libssh2                               1.11.1              h3dc7d44_0               conda-forge
  libtasn1                              4.19.0              hb7f2c08_0               conda-forge
  libtiff                               4.6.0               h684deea_2               conda-forge
  libunistring                          0.9.10              h0d85af4_0               conda-forge
  libvpx                                1.13.1              he965462_0               conda-forge
  libwebp-base                          1.4.0               h10d778d_0               conda-forge
  libxcb                                1.17.0              hf1f96e2_0               conda-forge
  libxml2                               2.12.7              hc603aa4_3               conda-forge
  libzlib                               1.3.1               hd23fc13_2               conda-forge
  libzopfli                             1.0.3               h046ec9c_0               conda-forge
  llvm-openmp                           19.1.4              ha54dae1_0               conda-forge
  llvmlite                              0.43.0              py311h25b8078_1          conda-forge
  lz4-c                                 1.9.4               hf0c8a7f_0               conda-forge
  markdown                              3.6                 pyhd8ed1ab_0             conda-forge
  markupsafe                            3.0.2               py311h8b4e8a7_0          conda-forge
  matplotlib-base                       3.9.2               py311h8b21175_2          conda-forge
  ml_dtypes                             0.2.0               py311hab14417_2          conda-forge
  msgpack-numpy                         0.4.8               pyhd8ed1ab_0             conda-forge
  msgpack-python                        1.1.0               py311hf2f7c97_0          conda-forge
  multidict                             6.1.0               py311h1cc1194_1          conda-forge
  munkres                               1.1.4               pyh9f0ad1d_0             conda-forge
  ncurses                               6.5                 hf036a51_1               conda-forge
  nettle                                3.9.1               h8e11ae5_0               conda-forge
  networkx                              3.4.2               pyh267e887_2             conda-forge
  numba                                 0.60.0              py311h0e5bd6a_0          conda-forge
  numexpr                               2.10.2              py311hdf8f80f_0          conda-forge
  numpy                                 1.26.4              py311hc43a94b_0          conda-forge
  oauthlib                              3.2.2               pyhd8ed1ab_0             conda-forge
  opencv                                4.9.0               py311h9073893_5          conda-forge
  openh264                              2.4.0               h93d8f39_0               conda-forge
  openjpeg                              2.5.2               h7310d3a_0               conda-forge
  openssl                               3.4.0               hd471939_0               conda-forge
  opt_einsum                            3.4.0               pyhd8ed1ab_0             conda-forge
  p11-kit                               0.24.1              h65f8906_0               conda-forge
  packaging                             24.2                pyhff2d567_1             conda-forge
  pandas                                2.2.3               py311haeb46be_1          conda-forge
  patsy                                 1.0.1               pyhff2d567_0             conda-forge
  pcre2                                 10.44               h7634a1b_2               conda-forge
  pillow                                10.4.0              py311h17ad1af_1          conda-forge
  pixman                                0.43.4              h73e2aa4_0               conda-forge
  propcache                             0.2.0               py311h3336109_2          conda-forge
  protobuf                              4.24.4              py311h021eaf5_0          conda-forge
  psutil                                6.1.0               py311h1314207_0          conda-forge
  pthread-stubs                         0.4                 h00291cd_1002            conda-forge
  pugixml                               1.14                he965462_0               conda-forge
  py-cpuinfo                            9.0.0               pyhd8ed1ab_0             conda-forge
  py-opencv                             4.9.0               py311h112db91_5          conda-forge
  pyasn1                                0.6.1               pyhd8ed1ab_1             conda-forge
  pyasn1-modules                        0.4.1               pyhd8ed1ab_0             conda-forge
  pycparser                             2.22                pyhd8ed1ab_0             conda-forge
  pyjwt                                 2.10.0              pyhff2d567_0             conda-forge
  pyopenssl                             24.2.1              pyhd8ed1ab_2             conda-forge
  pyparsing                             3.2.0               pyhd8ed1ab_1             conda-forge
  pysocks                               1.7.1               pyha2e5f31_6             conda-forge
  pytables                              3.9.2               py311h3cee394_1          conda-forge
  python                                3.11.10             ha513fb2_3_cpython       conda-forge
  python-dateutil                       2.9.0.post0         pyhff2d567_0             conda-forge
  python-flatbuffers                    24.3.25             pyh59ac667_0             conda-forge
  python-tzdata                         2024.2              pyhd8ed1ab_0             conda-forge
  python_abi                            3.11                5_cp311                  conda-forge
  pytz                                  2024.1              pyhd8ed1ab_0             conda-forge
  pyu2f                                 0.1.5               pyhd8ed1ab_0             conda-forge
  pywavelets                            1.7.0               py311hde34974_2          conda-forge
  pyyaml                                6.0.2               py311h3336109_1          conda-forge
  pyzmq                                 26.2.0              py311h4d3da15_3          conda-forge
  qhull                                 2020.2              h3c5361c_5               conda-forge
  rav1e                                 0.6.6               h7205ca4_2               conda-forge
  re2                                   2023.09.01          hb168e87_1               conda-forge
  readline                              8.2                 h9e318b2_1               conda-forge
  requests                              2.32.3              pyhd8ed1ab_0             conda-forge
  requests-oauthlib                     2.0.0               pyhd8ed1ab_0             conda-forge
  rsa                                   4.9                 pyhd8ed1ab_0             conda-forge
  ruamel.yaml                           0.18.6              py311h1314207_1          conda-forge
  ruamel.yaml.clib                      0.2.8               py311h1314207_1          conda-forge
  scikit-image                          0.24.0              py311hcf53e2f_3          conda-forge
  scikit-learn                          1.5.2               py311ha1d5734_1          conda-forge
  scipy                                 1.14.1              py311hed734c1_1          conda-forge
  setuptools                            75.6.0              pyhff2d567_0             conda-forge
  shapely                               2.0.6               py311h9a2ae1f_2          conda-forge
  six                                   1.16.0              pyh6c4a22f_0             conda-forge
  snappy                                1.1.10              h6dc393e_1               conda-forge
  statsmodels                           0.14.4              py311h0034819_0          conda-forge
  svt-av1                               1.8.0               h93d8f39_0               conda-forge
  tabulate                              0.9.0               pyhd8ed1ab_1             conda-forge
  tbb                                   2022.0.0            h0ec6371_0               conda-forge
  tensorboard                           2.15.2              pyhd8ed1ab_0             conda-forge
  tensorboard-data-server               0.7.0               py311h968b48f_2          conda-forge
  tensorflow                            2.15.0              cpu_py311h7a9ae38_2      conda-forge
  tensorflow-base                       2.15.0              cpu_py311hbca55e7_2      conda-forge
  tensorflow-estimator                  2.15.0              cpu_py311hd6d7b2b_2      conda-forge
  tensorpack                            0.11                pyhd8ed1ab_1             conda-forge
  termcolor                             2.5.0               pyhd8ed1ab_0             conda-forge
  tf_slim                               1.1.0.post20231128  pyhd8ed1ab_0             conda-forge
  threadpoolctl                         3.5.0               pyhc1e730c_0             conda-forge
  tifffile                              2024.9.20           pyhd8ed1ab_0             conda-forge
  tk                                    8.6.13              h1abcd95_1               conda-forge
  tqdm                                  4.67.1              pyhd8ed1ab_0             conda-forge
  typing-extensions                     4.12.2              hd8ed1ab_0               conda-forge
  typing_extensions                     4.12.2              pyha770c72_0             conda-forge
  tzdata                                2024b               hc8b5060_0               conda-forge
  unicodedata2                          15.1.0              py311h1314207_1          conda-forge
  urllib3                               2.2.3               pyhd8ed1ab_0             conda-forge
  werkzeug                              3.1.3               pyhff2d567_0             conda-forge
  wrapt                                 1.14.1              py311h5547dcb_1          conda-forge
  x264                                  1!164.3095          h775f41a_2               conda-forge
  x265                                  3.5                 hbb4e6a2_3               conda-forge
  xorg-libxau                           1.0.11              h00291cd_1               conda-forge
  xorg-libxdmcp                         1.1.5               h00291cd_0               conda-forge
  xz                                    5.2.6               h775f41a_0               conda-forge
  yaml                                  0.2.5               h0d85af4_2               conda-forge
  yarl                                  1.18.0              py311h4d7f069_0          conda-forge
  zeromq                                4.3.5               h7130eaa_7               conda-forge
  zfp                                   1.0.1               h469392a_2               conda-forge
  zipp                                  3.21.0              pyhd8ed1ab_0             conda-forge
  zlib                                  1.3.1               hd23fc13_2               conda-forge
  zlib-ng                               2.0.7               hb7f2c08_0               conda-forge
  zstandard                             0.23.0              py311hdf6fcd6_1          conda-forge
  zstd                                  1.5.6               h915ae27_0               conda-forge
```

### Environment info

```shell
❯ mamba info -p ~/.pixi/envs/deeplabcut

       libmamba version : 2.0.3
          mamba version : 2.0.3
           curl version : libcurl/8.10.1 OpenSSL/3.4.0 (SecureTransport) zlib/1.3.1 zstd/1.5.6 libssh2/1.11.0 nghttp2/1.64.0
     libarchive version : libarchive 3.7.4 zlib/1.2.13 liblzma/5.2.6 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.6
       envs directories : /Users/roaldarbol/.pixi/envs/mamba/envs
          package cache : /Users/roaldarbol/.pixi/envs/mamba/pkgs
                          /Users/roaldarbol/.mamba/pkgs
            environment : /Users/roaldarbol/.pixi/envs/deeplabcut
           env location : /Users/roaldarbol/.pixi/envs/deeplabcut
      user config files : /Users/roaldarbol/.mambarc
 populated config files :
       virtual packages : __unix=0=0
                          __osx=15.1=0
                          __archspec=1=x86_64_v4
               channels : https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
       base environment : /Users/roaldarbol/.pixi/envs/mamba
               platform : osx-64
```

**Comment by roaldarbol** [comment]
I guess the issue is that the GUI components are optional in the PyPi release (along with either tensorflow and in the 3.0rc torch). I'm not really sure how that's normally dealt with in conda-forge?

**Comment by hmaarrfk** [comment]
The GUI components in pypi are just Pyside6. 

I’ve patched a few things to allow for choice in the GUI. For example napari doesn’t deal well with Pyside6 so using both PySide6 and QtPy5 often gives you a bad time. 

In your environment install 


- qtpy
- pyside6 or pyqt5

Note that you may also have to limit the upper bound of tensorflow

**Comment by roaldarbol** [comment]
Ah, cool thanks! I'll try in an hour's time once the edits have sifted through to prefix.dev.

**Comment by roaldarbol** [comment]
@hmaarrfk I had misunderstood you, thought you were pushing the patches, but now see that they already existed. I got it working, but it needs a few more dependencies; it works with:
- `qtpy`
- `pyside6`
- `qdarkstyle`
- `napari`
- `napari-deeplabcut`

So the resulting pixi command looks like this:

```sh
pixi global install --with qtpy --with pyside6 --with qdarkstyle --with napari  --with napari-deeplabcut deeplabcut
```

**Comment by roaldarbol** [comment]
Sorry, maybe I closed the issue a bit prematurely. I think most users expect to use DeepLabCut with a GUI (although importantly not everyone), so is there a way to get around having to install all the extra dependencies? Maybe also having a `deeplabcut-headless` recipe?

**Comment by hmaarrfk** [comment]
No honestly I don’t really want to. 

Maintaining deeplabcut is already hard enough. You can create a new issue as a tutorial with your best practices to get things up and running. 

Beyond documentation’s of the packages to install, I don’t want to create a new package for this.

**Comment by roaldarbol** [comment]
Fair enough, no worries. I'll document it elsewhere and link to it once those materials are up and running.
